In [ ]:
import pandas as pd
import os

from utils.pandas_utils import saver

In [ ]:
preview = pd.read_csv("big_data/single-cell-tracks_exp1-6_noErbB2.csv.gz", compression="gzip")

In [3]:
preview

,Exp_ID,Image_Metadata_Site,track_id,Image_Metadata_T,Nuclear_size,ERKKTR_ratio,FoxO3A_ratio,objNuclei_Location_Center_X,objNuclei_Location_Center_Y
0,1,1,1,0,303.0000,0.704407,1.33383,932.211,875.248
1,1,1,1,1,333.0000,0.848242,1.33791,932.150,874.174
2,1,1,1,2,314.0000,1.059170,1.37627,932.376,873.787
3,1,1,1,3,322.0000,1.188000,1.35754,932.168,873.453
4,1,1,1,4,313.9990,1.205540,1.36695,931.146,872.885
...,...,...,...,...,...,...,...,...,...
35541643,6,24,1372,253,81.9999,1.287450,1.34448,698.317,223.537
35541644,6,24,1372,254,83.0000,1.265500,1.31116,697.506,224.217
35541645,6,24,1372,255,83.0000,1.263590,1.30931,697.410,223.988
35541646,6,24,1372,256,80.0002,1.249440,1.25123,696.400,224.488
35541647,6,24,1372,257,71.9998,1.232270,1.23352,696.069,223.958

In [4]:
main_df = preview[preview["Exp_ID"].isin([1]) & preview["Image_Metadata_Site"].isin([1])]
main_df

,Exp_ID,Image_Metadata_Site,track_id,Image_Metadata_T,Nuclear_size,ERKKTR_ratio,FoxO3A_ratio,objNuclei_Location_Center_X,objNuclei_Location_Center_Y
0,1,1,1,0,303.000,0.704407,1.33383,932.211,875.248
1,1,1,1,1,333.000,0.848242,1.33791,932.150,874.174
2,1,1,1,2,314.000,1.059170,1.37627,932.376,873.787
3,1,1,1,3,322.000,1.188000,1.35754,932.168,873.453
4,1,1,1,4,313.999,1.205540,1.36695,931.146,872.885
...,...,...,...,...,...,...,...,...,...
356627,1,1,2857,253,165.000,0.597341,1.32403,1019.050,771.624
356628,1,1,2857,254,192.000,0.587024,1.28853,1019.060,773.099
356629,1,1,2857,255,200.000,0.587822,1.28325,1019.100,773.540
356630,1,1,2857,256,192.000,0.579069,1.29542,1018.930,772.469
356631,1,1,2857,257,175.000,0.589269,1.31594,1018.850,771.611

In [15]:
saver(main_df, "main_df")

In [ ]:
pd.read_csv(f"main_df.csv")

,Exp_ID,Image_Metadata_Site,track_id,Image_Metadata_T,Nuclear_size,ERKKTR_ratio,FoxO3A_ratio,objNuclei_Location_Center_X,objNuclei_Location_Center_Y
0,1,1,1,0,303.000,0.704407,1.33383,932.211,875.248
1,1,1,1,1,333.000,0.848242,1.33791,932.150,874.174
2,1,1,1,2,314.000,1.059170,1.37627,932.376,873.787
3,1,1,1,3,322.000,1.188000,1.35754,932.168,873.453
4,1,1,1,4,313.999,1.205540,1.36695,931.146,872.885
...,...,...,...,...,...,...,...,...,...
356627,1,1,2857,253,165.000,0.597341,1.32403,1019.050,771.624
356628,1,1,2857,254,192.000,0.587024,1.28853,1019.060,773.099
356629,1,1,2857,255,200.000,0.587822,1.28325,1019.100,773.540
356630,1,1,2857,256,192.000,0.579069,1.29542,1018.930,772.469
356631,1,1,2857,257,175.000,0.589269,1.31594,1018.850,771.611